-- PostgreSQL baseline schema: tables
--
-- Equivalent to the state SQLite reaches after migrations 0001-0255. PostgreSQL
-- installations start from here instead of replaying the SQLite migration history.
--
-- Type choices are constrained by API compatibility rather than by what is most natural
-- in PostgreSQL - see db/pgsql/README.md. In short: amounts are DOUBLE PRECISION (NUMERIC
-- would serialise as a JSON string), flags are SMALLINT holding 0/1 (BOOLEAN would
-- serialise as true/false), and both would break the documented response schemas.

CREATE TABLE api_keys (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	api_key TEXT NOT NULL UNIQUE,
	user_id INTEGER NOT NULL,
	expires TIMESTAMP,
	last_used TIMESTAMP,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	key_type TEXT NOT NULL DEFAULT 'default',
	description TEXT
);

CREATE TABLE batteries (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	used_in TEXT,
	charge_interval_days INTEGER NOT NULL DEFAULT 0,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1))
);

CREATE TABLE battery_charge_cycles (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	battery_id INTEGER NOT NULL,
	tracked_time TIMESTAMP,
	undone SMALLINT NOT NULL DEFAULT 0 CHECK(undone IN (0, 1)),
	undone_timestamp TIMESTAMP,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

CREATE TABLE cache__products_average_price (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_id INTEGER,
	price DOUBLE PRECISION,

	UNIQUE(product_id)
);

CREATE TABLE cache__products_last_purchased (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_id INTEGER,
	amount DOUBLE PRECISION,
	best_before_date DATE,
	purchased_date DATE,
	price DOUBLE PRECISION,
	location_id INTEGER,
	shopping_location_id INTEGER,

	UNIQUE(product_id)
);

CREATE TABLE cache__quantity_unit_conversions_resolved (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_id INTEGER,
	from_qu_id INTEGER,
	from_qu_name TEXT,
	from_qu_name_plural TEXT,
	to_qu_id INTEGER,
	to_qu_name TEXT,
	to_qu_name_plural TEXT,
	factor TEXT,
	path TEXT
);

CREATE TABLE chores (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	period_type TEXT NOT NULL,
	period_days INTEGER,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	period_config TEXT,
	track_date_only SMALLINT DEFAULT 0,
	rollover SMALLINT DEFAULT 0,
	assignment_type TEXT,
	assignment_config TEXT,
	next_execution_assigned_to_user_id INTEGER,
	consume_product_on_execution SMALLINT NOT NULL DEFAULT 0,
	-- Declared TINYINT upstream, but this holds a product id and so must not be SMALLINT
	product_id INTEGER,
	product_amount DOUBLE PRECISION,
	period_interval INTEGER NOT NULL DEFAULT 1 CHECK(period_interval > 0),
	active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1)),
	start_date TIMESTAMP,
	rescheduled_date TIMESTAMP,
	rescheduled_next_execution_assigned_to_user_id INTEGER
);

CREATE TABLE chores_log (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	chore_id INTEGER NOT NULL,
	tracked_time TIMESTAMP,
	done_by_user_id INTEGER,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	undone SMALLINT NOT NULL DEFAULT 0 CHECK(undone IN (0, 1)),
	undone_timestamp TIMESTAMP,
	skipped SMALLINT NOT NULL DEFAULT 0 CHECK(skipped IN (0, 1)),
	scheduled_execution_time TIMESTAMP
);

CREATE TABLE equipment (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	instruction_manual_file_name TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

CREATE TABLE locations (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	is_freezer SMALLINT NOT NULL DEFAULT 0,
	active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1))
);

CREATE TABLE meal_plan (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	day DATE NOT NULL,
	type TEXT DEFAULT 'recipe',
	recipe_id INTEGER,
	recipe_servings DOUBLE PRECISION DEFAULT 1,
	note TEXT,
	product_id INTEGER,
	product_amount DOUBLE PRECISION DEFAULT 0,
	product_qu_id INTEGER,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	done SMALLINT NOT NULL DEFAULT 0 CHECK(done IN (0, 1)),
	section_id INTEGER NOT NULL DEFAULT -1
);

CREATE TABLE meal_plan_sections (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	sort_number INTEGER,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	time_info TEXT
);

-- The "migrations" table is deliberately absent: DatabaseMigrationService creates it for
-- every engine before the baseline is loaded, since it is what records that the baseline
-- was applied at all.

CREATE TABLE permission_hierarchy (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	parent INTEGER NULL -- If the user has the parent permission, the user also has the child permission
);

CREATE TABLE product_barcodes (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_id INTEGER NOT NULL,
	barcode TEXT NOT NULL,
	qu_id INTEGER,
	amount DOUBLE PRECISION,
	shopping_location_id INTEGER,
	last_price DOUBLE PRECISION,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	note TEXT
);

CREATE TABLE product_groups (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1))
);

CREATE TABLE products (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	product_group_id INTEGER,
	active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1)),
	location_id INTEGER NOT NULL,
	shopping_location_id INTEGER,
	qu_id_purchase INTEGER NOT NULL,
	qu_id_stock INTEGER NOT NULL,
	-- Declared INTEGER upstream, but SQLite stores fractional values here and the
	-- OpenAPI spec documents it as "number"
	min_stock_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
	default_best_before_days INTEGER NOT NULL DEFAULT 0,
	default_best_before_days_after_open INTEGER NOT NULL DEFAULT 0,
	default_best_before_days_after_freezing INTEGER NOT NULL DEFAULT 0,
	default_best_before_days_after_thawing INTEGER NOT NULL DEFAULT 0,
	picture_file_name TEXT,
	enable_tare_weight_handling SMALLINT NOT NULL DEFAULT 0,
	tare_weight DOUBLE PRECISION NOT NULL DEFAULT 0,
	not_check_stock_fulfillment_for_recipes SMALLINT DEFAULT 0,
	parent_product_id INTEGER,
	calories DOUBLE PRECISION,
	cumulate_min_stock_amount_of_sub_products SMALLINT DEFAULT 0,
	due_type SMALLINT NOT NULL DEFAULT 1 CHECK(due_type IN (1, 2)),
	quick_consume_amount DOUBLE PRECISION NOT NULL DEFAULT 1,
	hide_on_stock_overview SMALLINT NOT NULL DEFAULT 0 CHECK(hide_on_stock_overview IN (0, 1)),
	default_stock_label_type INTEGER NOT NULL DEFAULT 0,
	should_not_be_frozen SMALLINT NOT NULL DEFAULT 0 CHECK(should_not_be_frozen IN (0, 1)),
	treat_opened_as_out_of_stock SMALLINT NOT NULL DEFAULT 1 CHECK(treat_opened_as_out_of_stock IN (0, 1)),
	no_own_stock SMALLINT NOT NULL DEFAULT 0 CHECK(no_own_stock IN (0, 1)),
	default_consume_location_id INTEGER,
	move_on_open SMALLINT NOT NULL DEFAULT 0 CHECK(move_on_open IN (0, 1)),
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	qu_id_consume INTEGER,
	auto_reprint_stock_label SMALLINT NOT NULL DEFAULT 0 CHECK(auto_reprint_stock_label IN (0, 1)),
	quick_open_amount DOUBLE PRECISION NOT NULL DEFAULT 1,
	qu_id_price INTEGER,
	disable_open SMALLINT NOT NULL DEFAULT 0 CHECK(disable_open IN (0, 1)),
	default_purchase_price_type SMALLINT NOT NULL DEFAULT 1 CHECK(default_purchase_price_type IN (1, 2, 3))
);

CREATE TABLE quantity_unit_conversions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	from_qu_id INTEGER NOT NULL,
	to_qu_id INTEGER NOT NULL,
	factor DOUBLE PRECISION NOT NULL,
	product_id INTEGER,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

CREATE TABLE quantity_units (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	name_plural TEXT,
	plural_forms TEXT,
	active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1))
);

CREATE TABLE recipes (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	description TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	picture_file_name TEXT,
	base_servings DOUBLE PRECISION DEFAULT 1,
	desired_servings DOUBLE PRECISION DEFAULT 1,
	not_check_shoppinglist SMALLINT NOT NULL DEFAULT 0,
	type TEXT DEFAULT 'normal',
	product_id INTEGER
);

CREATE TABLE recipes_nestings (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	recipe_id INTEGER NOT NULL,
	includes_recipe_id INTEGER NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	servings DOUBLE PRECISION DEFAULT 1,

	UNIQUE(recipe_id, includes_recipe_id)
);

CREATE TABLE recipes_pos (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	recipe_id INTEGER NOT NULL,
	product_id INTEGER NOT NULL,
	amount DOUBLE PRECISION NOT NULL DEFAULT 0,
	note TEXT,
	qu_id INTEGER,
	only_check_single_unit_in_stock SMALLINT NOT NULL DEFAULT 0,
	ingredient_group TEXT,
	not_check_stock_fulfillment SMALLINT NOT NULL DEFAULT 0,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	variable_amount TEXT,
	price_factor DOUBLE PRECISION NOT NULL DEFAULT 1,
	round_up SMALLINT NOT NULL DEFAULT 0 CHECK(round_up IN (0, 1))
);

CREATE TABLE sessions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_key TEXT NOT NULL UNIQUE,
	user_id INTEGER NOT NULL,
	expires TIMESTAMP,
	last_used TIMESTAMP,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

CREATE TABLE shopping_list (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_id INTEGER,
	note TEXT,
	amount DOUBLE PRECISION NOT NULL DEFAULT 0,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	shopping_list_id INTEGER DEFAULT 1,
	done INTEGER DEFAULT 0,
	qu_id INTEGER
);

CREATE TABLE shopping_lists (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

CREATE TABLE shopping_locations (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1))
);

CREATE TABLE stock (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_id INTEGER NOT NULL,
	amount DOUBLE PRECISION NOT NULL,
	best_before_date DATE,
	purchased_date DATE DEFAULT CURRENT_DATE,
	stock_id TEXT NOT NULL,
	price DOUBLE PRECISION,
	open SMALLINT NOT NULL DEFAULT 0 CHECK(open IN (0, 1)),
	-- DATETIME upstream, but only ever holds a date and the OpenAPI spec says
	-- format: date. As TIMESTAMP, PostgreSQL would render it "2026-08-26 00:00:00"
	-- where SQLite returns "2026-08-26", changing the API response.
	opened_date DATE,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	location_id INTEGER,
	shopping_location_id INTEGER,
	note TEXT
);

CREATE TABLE stock_log (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_id INTEGER NOT NULL,
	amount DOUBLE PRECISION NOT NULL,
	best_before_date DATE,
	purchased_date DATE,
	used_date DATE,
	spoiled INTEGER NOT NULL DEFAULT 0,
	stock_id TEXT NOT NULL,
	transaction_type TEXT NOT NULL,
	price DOUBLE PRECISION,
	undone SMALLINT NOT NULL DEFAULT 0 CHECK(undone IN (0, 1)),
	undone_timestamp TIMESTAMP,
	opened_date DATE, -- See the note on stock.opened_date
	location_id INTEGER,
	recipe_id INTEGER,
	correlation_id TEXT,
	transaction_id TEXT,
	stock_row_id INTEGER,
	shopping_location_id INTEGER,
	user_id INTEGER NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	note TEXT
);

CREATE TABLE task_categories (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1))
);

CREATE TABLE tasks (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	description TEXT,
	-- DATETIME upstream and documented as date-time, but the task form writes
	-- date('Y-m-d') only, so DATE reproduces the existing API response exactly.
	-- (chores.start_date stays TIMESTAMP - that form does write a time.)
	due_date DATE,
	done SMALLINT NOT NULL DEFAULT 0 CHECK(done IN (0, 1)),
	done_timestamp TIMESTAMP,
	category_id INTEGER,
	assigned_to_user_id INTEGER,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

CREATE TABLE user_permissions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	permission_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,

	UNIQUE (user_id, permission_id)
);

CREATE TABLE user_settings (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL,
	key TEXT NOT NULL,
	value TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	row_updated_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),

	UNIQUE(user_id, key)
);

CREATE TABLE userentities (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	caption TEXT NOT NULL,
	description TEXT,
	show_in_sidebar_menu SMALLINT NOT NULL DEFAULT 1,
	icon_css_class TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),

	UNIQUE(name)
);

CREATE TABLE userfield_values (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	field_id INTEGER NOT NULL,
	object_id TEXT NOT NULL,
	value TEXT NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),

	UNIQUE(field_id, object_id)
);

CREATE TABLE userfields (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	entity TEXT NOT NULL,
	name TEXT NOT NULL,
	caption TEXT NOT NULL,
	type TEXT NOT NULL,
	show_as_column_in_tables SMALLINT NOT NULL DEFAULT 0,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	config TEXT,
	sort_number INTEGER,
	input_required SMALLINT NOT NULL DEFAULT 0 CHECK(input_required IN (0, 1)),
	default_value TEXT,

	UNIQUE(entity, name)
);

CREATE TABLE userobjects (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userentity_id INTEGER NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

CREATE TABLE users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT NOT NULL UNIQUE,
	first_name TEXT,
	last_name TEXT,
	password TEXT NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	picture_file_name TEXT
);
