-- Per-product MQTT entities: the opt-in flag, and the record of what has been published.
--
-- The PostgreSQL half of the pair. See migrations/0257.sqlite.sql for why these two tables
-- exist and why the flag is a side table rather than a column on products; the reasoning is
-- the same on both engines and is not repeated here.
--
-- This is a pair rather than one portable file for one reason only: generated primary keys
-- are spelled differently and there is no spelling both engines accept. SQLite's INTEGER
-- PRIMARY KEY AUTOINCREMENT assigns ids on insert; PostgreSQL's INTEGER PRIMARY KEY does
-- not, and needs GENERATED BY DEFAULT AS IDENTITY - which is exactly how the baseline
-- spells every other id column (db/pgsql/baseline/01_tables.sql). Everything else about
-- these two files is the same schema, so the pair is complete and needs no
-- @engine-exclusive marker: both engines run migration 257 and end up with the same
-- logical tables.
--
-- Types follow the baseline's own conventions rather than the closest PostgreSQL type:
-- TEXT for strings and TIMESTAMP defaulted to a second-truncated LOCALTIMESTAMP, because
-- the timestamps in this schema are local times everywhere.

CREATE TABLE mqtt_product_entities (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_id INTEGER NOT NULL UNIQUE,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

CREATE TABLE mqtt_published_entities (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	object_id TEXT NOT NULL UNIQUE,
	payload_hash TEXT NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);
