-- The files table: uploaded files as BYTEA, so that the application needs no volume.
--
-- Product, recipe and user pictures, user files and equipment manuals live under
-- <data path>/storage today, which is the last thing keeping a persistent volume attached
-- to a pod that otherwise has no state on disk (plan 10). It is also two backup streams -
-- picture_file_name in the database, the bytes on a volume - that can disagree after a
-- crash, where one pg_dump captures both.
--
-- The table is only read when FILE_STORAGE = "database"; it exists either way, so that
-- flipping the setting is a configuration change rather than a migration.
--
-- file_group rather than "group", which is reserved. size_bytes is stored rather than
-- derived so that bin/victual-files-import can decide what it has already imported
-- without pulling every file's content back out of the database.
--
-- is_derivative marks the cached downscaled copies, which are ordinary rows under today's
-- exact "<name>__downscaledto<h>x<w>.<ext>" naming. They are all regenerable, so the flag
-- is what lets every thumbnail be dropped with one statement and a dump be trimmed.
-- SMALLINT holding 0/1 rather than BOOLEAN, matching every other flag in this schema
-- (db/pgsql/README.md).
--
-- Deliberately NOT an ExposedEntity: nothing serves this table as JSON, and a generic CRUD
-- route over a BYTEA column would be a new way to move bytes past the files API's
-- permission and content checks (sweep S2).
--
-- @engine-exclusive
-- PostgreSQL only, deliberately, and SQLite needs no counterpart because the
-- configuration that would use this table cannot exist on SQLite: ConfigurationValidator
-- refuses FILE_STORAGE = "database" unless DB_DRIVER is "pgsql", so a SQLite installation
-- can only ever run the filesystem backend. A SQLite BLOB counterpart would therefore be
-- a table nothing could read - and ADR-0008 has since made PostgreSQL the only runtime
-- engine, which is why plan 01 could decide bytea on its merits. The exemption is
-- recorded in db/pgsql/README.md next to the rule, and this is the first engine-exclusive
-- TABLE rather than the first engine-exclusive migration (0256.sqlite.sql was a view).

CREATE TABLE files (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	file_group TEXT NOT NULL,
	name TEXT NOT NULL,
	mime_type TEXT,
	size_bytes INTEGER NOT NULL,
	is_derivative SMALLINT NOT NULL DEFAULT 0 CHECK(is_derivative IN (0, 1)),
	content BYTEA NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	UNIQUE(file_group, name)
);
