-- The outbox: events that have been committed but not yet delivered to a consumer.
--
-- The PostgreSQL half of the pair. See migrations/0259.sqlite.sql for why this table exists
-- and why the row is written inside the booking's transaction; the reasoning is the same on
-- both engines and is not repeated here.
--
-- A pair rather than one portable file for the same single reason migration 257 is:
-- generated primary keys have no spelling both engines accept. Everything else about the
-- two files is the same schema, so the pair is complete and needs no @engine-exclusive
-- marker - both engines run migration 259 and end up with the same logical table.
--
-- Types follow the baseline's conventions: TEXT for strings, TIMESTAMP for local times.

CREATE TABLE outbox (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	event_type TEXT NOT NULL,
	payload TEXT NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	delivered_at TIMESTAMP,
	attempts INTEGER NOT NULL DEFAULT 0,
	last_error TEXT
);

CREATE INDEX outbox_undelivered ON outbox (delivered_at, id);
