-- Failed login attempts, so that guessing a password is rate limited.
--
-- The PostgreSQL half of the pair. See migrations/0262.sqlite.sql for why this table
-- exists at all, why it is a table rather than a counter that a scale-to-zero pod would
-- reset for free, and why the address column records REMOTE_ADDR rather than a header a
-- client can set; the reasoning is the same on both engines and is not repeated here.
--
-- A pair rather than one portable file for the same single reason migrations 257, 259 and
-- 262's SQLite half are: generated primary keys have no spelling both engines accept.
-- Everything else about the two files is the same schema, so the pair is complete and
-- needs no @engine-exclusive marker - both engines run migration 262 and end up with the
-- same logical table.
--
-- Types follow the baseline's conventions: TEXT for strings, TIMESTAMP for local times.

CREATE TABLE login_attempts (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT NOT NULL,
	ip_address TEXT NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

CREATE INDEX login_attempts_username ON login_attempts (username, row_created_timestamp);
CREATE INDEX login_attempts_ip_address ON login_attempts (ip_address, row_created_timestamp);
