-- Failed login attempts per username, so that guessing a password is rate limited.
--
-- The PostgreSQL half of the pair. See migrations/0262.sqlite.sql for why this is a table
-- rather than a counter a scale-to-zero pod would reset for free, and for why there is
-- deliberately no per-address counter - behind a reverse proxy REMOTE_ADDR is the proxy,
-- so one would hold the whole instance rather than one client, and rate limiting an
-- address belongs at the layer that knows which address it is. The reasoning is the same
-- on both engines and is not repeated here.
--
-- A pair rather than one portable file for the same single reason migrations 257, 259 and
-- 263 are: generated primary keys have no spelling both engines accept. Everything else
-- about the two files is the same schema, so the pair is complete and needs no
-- @engine-exclusive marker - both engines run migration 262 and end up with the same
-- logical table.
--
-- Types follow the baseline's conventions: TEXT for strings, TIMESTAMP for local times.

CREATE TABLE login_attempts (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

CREATE INDEX login_attempts_username ON login_attempts (username, row_created_timestamp);
